# -*- coding: utf-8 -*-
"""Day 74 - Google Trends and Data Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bltVP1k8e03WdPOgEDTty4I0SlUgZ93

# Introduction

Google Trends gives us an estimate of search volume. Let's explore if search popularity relates to other kinds of data. Perhaps there are patterns in Google's search volume and the price of Bitcoin or a hot stock like Tesla. Perhaps search volume for the term "Unemployment Benefits" can tell us something about the actual unemployment rate? 

Data Sources: <br>
<ul>
<li> <a href="https://fred.stlouisfed.org/series/UNRATE/">Unemployment Rate from FRED</a></li>
<li> <a href="https://trends.google.com/trends/explore">Google Trends</a> </li>  
<li> <a href="https://finance.yahoo.com/quote/TSLA/history?p=TSLA">Yahoo Finance for Tesla Stock Price</a> </li>    
<li> <a href="https://finance.yahoo.com/quote/BTC-USD/history?p=BTC-USD">Yahoo Finance for Bitcoin Stock Price</a> </li>
</ul>

# Import Statements
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Format float
pd.options.display.float_format = '{:,.2f}'.format

"""# Read the Data

Download and add the .csv files.
"""

df_tesla = pd.read_csv('data/TESLA Search Trend vs Price.csv')

df_btc_search = pd.read_csv('data/Bitcoin Search Trend.csv')
df_btc_price = pd.read_csv('data/Daily Bitcoin Price.csv')

df_unemployment = pd.read_csv('data/UE Benefits Search vs UE Rate 2004-19.csv')

"""# Data Exploration

### Tesla

**Challenge**: <br>
<ul>
<li>What are the shapes of the dataframes? </li>
<li>How many rows and columns? </li>
<li>What are the column names? </li>
<li>Complete the f-string to show the largest/smallest number in the search data column</li> 
<li>Try the <code>.describe()</code> function to see some useful descriptive statistics</li>
<li>What is the periodicity of the time series data (daily, weekly, monthly)? </li>
<li>What does a value of 100 in the Google Trend search popularity actually mean?</li>
</ul>
"""

# TSLA
# What are the shapes of the dataframes?
print(f'Shapes of TSLA df: {df_tesla.shape}')

# How many rows and columns?
print(f'TSLA df rows: {df_tesla.shape[0]}')
print(f'TSLA df columns: {df_tesla.shape[1]}')

# What are the column names?
print(f'TSLA df column names: {df_tesla.columns.values}')

# Complete the f-string to show the largest/smallest number in the search data column
print(f'Largest value for Tesla in Web Search: {df_tesla.TSLA_WEB_SEARCH.max()}')
print(f'Smallest value for Tesla in Web Search: {df_tesla.TSLA_WEB_SEARCH.min()}')

# Try the .describe() function to see some useful descriptive statistics
print(df_tesla.describe())

# What is the periodicity of the time series data (daily, weekly, monthly)?
print(df_tesla.head())

"""### Unemployment Data"""

# Unemployment
# What are the shapes of the dataframes?
print(f'Shapes of Unemployment df: {df_unemployment.shape}')

# How many rows and columns?
print(f'Unemployment df rows: {df_unemployment.shape[0]}')
print(f'Unemployment df columns: {df_unemployment.shape[1]}')

# What are the column names?
print(f'Unemployment df column names: {df_unemployment.columns.values}')

# Complete the f-string to show the largest/smallest number in the search data column
print(f'Largest value for Unemployment in Web Search: {df_unemployment.UE_BENEFITS_WEB_SEARCH.max()}')
print(f'Smallest value for Unemployment in Web Search: {df_unemployment.UE_BENEFITS_WEB_SEARCH.min()}')

# Try the .describe() function to see some useful descriptive statistics
print(df_unemployment.describe())

# What is the periodicity of the time series data (daily, weekly, monthly)?
print(df_unemployment.head())

"""### Bitcoin"""

# BTC
# What are the shapes of the dataframes?
print(f'Shapes of BTC df: {df_btc_search.shape}')

# How many rows and columns?
print(f'Unemployment df rows: {df_btc_search.shape[0]}')
print(f'Unemployment df columns: {df_btc_search.shape[1]}')

# What are the column names?
print(f'Unemployment df column names: {df_btc_search.columns.values}')

# Complete the f-string to show the largest/smallest number in the search data column
print(f'Largest value for BTC in Web Search: {df_btc_search.BTC_NEWS_SEARCH.max()}')
print(f'Smallest value for BTC in Web Search: {df_btc_search.BTC_NEWS_SEARCH.min()}')

# Try the .describe() function to see some useful descriptive statistics
print(df_btc_search.describe())

# What is the periodicity of the time series data (daily, weekly, monthly)?
print(df_btc_search.head())

"""# Data Cleaning

### Check for Missing Values

**Challenge**: Are there any missing values in any of the dataframes? If so, which row/rows have missing values? How many missing values are there?
"""

print(f'Missing values for Tesla?: {df_tesla.isna().values.any()}\n')
print(f'Missing values for U/E?: {df_unemployment.isna().values.any()}\n')
print(f'Missing values for BTC Search?: {df_btc_search.isna().values.any()}\n')

print(f'Missing values for BTC price?: {df_btc_price.isna().values.any()}')

print(f'Number of missing values: {df_btc_price.isna().values.sum()}')

"""**Challenge**: Remove any missing values that you found. """

df_btc_price.dropna(inplace=True)

"""### Convert Strings to DateTime Objects

**Challenge**: Check the data type of the entries in the DataFrame MONTH or DATE columns. Convert any strings in to Datetime objects. Do this for all 4 DataFrames. Double check if your type conversion was successful.
"""

# TSLA
print('TSLA:')
print(f'Before: {df_tesla.MONTH.dtype}')
df_tesla.MONTH = pd.to_datetime(df_tesla.MONTH)
print(f'After: {df_tesla.MONTH.dtype}')
print('\n')

# U/E
print('U/E:')
print(f'Before: {df_unemployment.MONTH.dtype}')
df_unemployment.MONTH = pd.to_datetime(df_unemployment.MONTH)
print(f'After: {df_unemployment.MONTH.dtype}')
print('\n')

# BTC Search
print('BTC Search:')
print(f'Before: {df_btc_search.MONTH.dtype}')
df_btc_search.MONTH = pd.to_datetime(df_btc_search.MONTH)
print(f'After: {df_btc_search.MONTH.dtype}')
print('\n')

# BTC Price
print('BTC Price:')
print(f'Before: {df_btc_price.DATE.dtype}')
df_btc_price.DATE = pd.to_datetime(df_btc_price.DATE)
print(f'After: {df_btc_price.DATE.dtype}')

"""### Converting from Daily to Monthly Data

[Pandas .resample() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) <br>
"""

df_btc_monthly = df_btc_price.resample('M', on='DATE').last()

print(df_btc_monthly.shape)
df_btc_monthly.head()

"""# Data Visualisation

### Notebook Formatting & Style Helpers
"""

# Create locators for ticks on the time axis

# Register date converters to avoid warning messages

"""### Tesla Stock Price v.s. Search Volume

**Challenge:** Plot the Tesla stock price against the Tesla search volume using a line chart and two different axes. Label one axis 'TSLA Stock Price' and the other 'Search Trend'.

**Challenge**: Make the chart larger and easier to read. 
1. Increase the figure size (e.g., to 14 by 8). 
2. Increase the font sizes for the labels and the ticks on the x-axis to 14. 
3. Rotate the text on the x-axis by 45 degrees. 
4. Make the lines on the chart thicker. 
5. Add a title that reads 'Tesla Web Search vs Price'
6. Keep the chart looking sharp by changing the dots-per-inch or [DPI value](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.figure.html). 
7. Set minimum and maximum values for the y and x axis. Hint: check out methods like [set_xlim()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_xlim.html). 
8. Finally use [plt.show()](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.show.html) to display the chart below the cell instead of relying on the automatic notebook output.
"""

years = mdates.YearLocator()
months = mdates.MonthLocator()
years_fmt = mdates.DateFormatter('%Y')

plt.figure(figsize=(14, 8), dpi=120)
plt.title('Tesla Web Search vs Price', fontsize=16)
plt.xticks(fontsize=14, rotation=45)

ax1 = plt.gca()
ax2 = ax1.twinx()

ax1.xaxis.set_major_locator(years)
ax1.xaxis.set_major_formatter(years_fmt)
ax1.xaxis.set_minor_locator(months)

ax1.set_ylabel('TSLA Stock Price', color='#002B7F', fontsize=14)
ax2.set_ylabel('Search Trend', color='#CE1126', fontsize=14)

ax1.plot(df_tesla.MONTH, df_tesla.TSLA_USD_CLOSE, color='#002B7F', linewidth=3)
ax2.plot(df_tesla.MONTH, df_tesla.TSLA_WEB_SEARCH, color='#CE1126', linewidth=3)

ax1.set_ylim([0,600])
ax1.set_xlim([df_tesla.MONTH.min(), df_tesla.MONTH.max()])

plt.show()

"""### Bitcoin (BTC) Price v.s. Search Volume

**Challenge**: Create the same chart for the Bitcoin Prices vs. Search volumes. <br>
1. Modify the chart title to read 'Bitcoin News Search vs Resampled Price' <br>
2. Change the y-axis label to 'BTC Price' <br>
3. Change the y- and x-axis limits to improve the appearance <br>
4. Investigate the [linestyles](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.plot.html ) to make the BTC price a dashed line <br>
5. Investigate the [marker types](https://matplotlib.org/3.2.1/api/markers_api.html) to make the search datapoints little circles <br>
6. Were big increases in searches for Bitcoin accompanied by big increases in the price?
"""

plt.figure(figsize=(14, 8), dpi=120)
plt.title('Bitcoin News Search vs Resampled Price', fontsize=14)
plt.xticks(rotation=45)

ax1 = plt.gca()
ax2 = ax1.twinx()

ax1.xaxis.set_major_locator(years)
ax1.xaxis.set_major_formatter(years_fmt)
ax1.xaxis.set_minor_locator(months)

ax1.set_ylabel('Search Trend', color='#002B7F', fontsize=14)
ax2.set_ylabel('BTC Price', color='#CE1126', fontsize=14)

ax1.plot(df_btc_search.MONTH, df_btc_search.BTC_NEWS_SEARCH, color='#002B7F', linewidth=3, marker='o')
ax2.plot(df_btc_monthly.DATE, df_btc_monthly.CLOSE, color='#CE1126', linewidth=3, linestyle='dashed')

ax1.set_ylim([0, 100])
ax2.set_ylim([0, 14000])
ax2.set_xlim([df_btc_monthly.DATE.min(), df_btc_monthly.DATE.max()])

plt.show()

"""### Unemployement Benefits Search vs. Actual Unemployment in the U.S.

**Challenge** Plot the search for "unemployment benefits" against the unemployment rate. 
1. Change the title to: Monthly Search of "Unemployment Benefits" in the U.S. vs the U/E Rate <br>
2. Change the y-axis label to: FRED U/E Rate <br>
3. Change the axis limits <br>
4. Add a grey [grid](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.grid.html) to the chart to better see the years and the U/E rate values. Use dashes for the line style<br> 
5. Can you discern any seasonality in the searches? Is there a pattern?
"""

plt.figure(figsize=(14, 8), dpi=120)
plt.title('Monthly Search of "Unemployment Benefits" in the U.S. vs the U/E Rate', fontsize=14)
plt.xticks(rotation=45)
plt.grid(color='#808080', linestyle='-', linewidth=1)

ax1 = plt.gca()
ax2 = ax1.twinx()

ax1.xaxis.set_major_locator(years)
ax1.xaxis.set_major_formatter(years_fmt)
ax1.xaxis.set_minor_locator(months)

ax1.set_ylabel('Search Trend', color='#002B7F', fontsize=14)
ax2.set_ylabel('FRED U/E Rate', color='#CE1126', fontsize=14)

ax1.plot(df_unemployment.MONTH, df_unemployment.UE_BENEFITS_WEB_SEARCH, color='#002B7F', linewidth=3, marker='o')
ax2.plot(df_unemployment.MONTH, df_unemployment.UNRATE, color='#CE1126', linewidth=3, linestyle='dashed')

ax2.set_xlim([df_unemployment.MONTH.min(), df_unemployment.MONTH.max()])

plt.show()

"""**Challenge**: Calculate the 3-month or 6-month rolling average for the web searches. Plot the 6-month rolling average search data against the actual unemployment. What do you see in the chart? Which line moves first?

"""

plt.figure(figsize=(14, 8), dpi=120)
plt.title('Monthly Search of "Unemployment Benefits" in the U.S. vs the U/E Rate', fontsize=14)
plt.xticks(rotation=45)
plt.grid(color='#808080', linestyle='-', linewidth=1)

ax1 = plt.gca()
ax2 = ax1.twinx()

ax1.xaxis.set_major_locator(years)
ax1.xaxis.set_major_formatter(years_fmt)
ax1.xaxis.set_minor_locator(months)

ax1.set_ylabel('Search Trend', color='#002B7F', fontsize=14)
ax2.set_ylabel('FRED U/E Rate', color='#CE1126', fontsize=14)

roll_df = df_unemployment[['UE_BENEFITS_WEB_SEARCH', 'UNRATE']].rolling(window=6).mean()

ax1.plot(df_unemployment.MONTH, roll_df.UE_BENEFITS_WEB_SEARCH, color='#002B7F', linewidth=3, marker='o')
ax2.plot(df_unemployment.MONTH, roll_df.UNRATE, color='#CE1126', linewidth=3, linestyle='dashed')

ax2.set_xlim([df_unemployment.MONTH.min(), df_unemployment.MONTH.max()])

plt.show()

"""### Including 2020 in Unemployment Charts

**Challenge**: Read the data in the 'UE Benefits Search vs UE Rate 2004-20.csv' into a DataFrame. Convert the MONTH column to Pandas Datetime objects and then plot the chart. What do you see?
"""

df_ue_2020 = pd.read_csv('data/UE Benefits Search vs UE Rate 2004-20.csv')
df_ue_2020.MONTH = pd.to_datetime(df_ue_2020.MONTH)

plt.figure(figsize=(14,8), dpi=120)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14, rotation=45)
plt.title('Monthly US "Unemployment Benefits" Web Search vs UNRATE incl 2020', fontsize=18)
 
ax1 = plt.gca()
ax2 = ax1.twinx()
 
ax1.set_ylabel('FRED U/E Rate', color='purple', fontsize=16)
ax2.set_ylabel('Search Trend', color='skyblue', fontsize=16)
 
ax1.set_xlim([df_ue_2020.MONTH.min(), df_ue_2020.MONTH.max()])
 
ax1.plot(df_ue_2020.MONTH, df_ue_2020.UNRATE, 'purple', linewidth=3)
ax2.plot(df_ue_2020.MONTH, df_ue_2020.UE_BENEFITS_WEB_SEARCH, 'skyblue', linewidth=3)
 
plt.show()